[package]
name = "bitcask-rs"
version = "0.1.0"
edition = "2021"

[[example]]
name = "basic_operations"
path = "examples/basic_operations.rs"

[dependencies]
bytes = "1.10.0"
crc32fast = "1.4.2"
env_logger = "0.11.6"
log = "0.4.25"
parking_lot = "0.12.3"
prost = "0.13.4"
thiserror = "2.0.11"
